### ISSUE TITLE
in `const_get': wrong constant name  (NameError)

### ISSUE THREAD

**Issue by stephanecollot** [tessellator/so2db#5]
Hi,

I'm using Januray 2014 data dump, with the new-format-uplift branch and the 'Installing Locally' in the wiki. My Ruby version is ```ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]```
Here is what I get:

```
$ so2pg -O -R -H postgres1....amazonaws.com -P 5432 -d ... -u ... -p ... -D ../data/xml/
-- create_table(:badges)
   -> 0.0636s
-- create_table(:comments)
   -> 0.0192s
-- create_table(:posts)
   -> 0.0194s
-- create_table(:post_links)
   -> 0.0108s
-- create_table(:post_history)
   -> 0.0170s
-- create_table(:users)
   -> 0.0167s
-- create_table(:votes)
   -> 0.0111s
Importing file Votes.xml...
   -> 1987.014231645s
Importing file Badges.xml...
   -> 354.279034548s
Importing file Users.xml...
   -> 191.111664532s
Importing file Post.xml...
/usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db/models.rb:85:in `const_get': wrong constant name  (NameError)
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db/models.rb:85:in `find_class'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db/formatter.rb:50:in `value_str'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2pg.rb:51:in `import_stream'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db.rb:84:in `block in import_data'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db.rb:82:in `each'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db.rb:82:in `import_data'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db.rb:60:in `import'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2pg.rb:35:in `import_from_argv'
        from /usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/bin/so2pg:5:in `<top (required)>'
        from /usr/local/bin/so2pg:23:in `load'
        from /usr/local/bin/so2pg:23:in `<main>'
```

Should I modify this line in ```/usr/local/share/ruby/gems/2.0/gems/so2db-0.1.0/lib/so2db/models.rb```?
```
    @@map = { "badges" => :Badge, "comments" => :Comment,
              "posthistory" => :PostHistory, "posts" => :Post,
              "postlinks" => :PostLink, "users" => :User,
              "votes" => :Vote }
```

Here is my xml directory:
```
total 98G
-rw-rw-r-- 1 user user 1.1G Apr 24 06:00 Badges.xml
-rw-rw-r-- 1 user user 9.0G Apr 24 07:20 Comments.xml
-rw-rw-r-- 1 user user  52G Apr 24 07:11 PostHistory.xml
-rw-rw-r-- 1 user user 264M Apr 24 06:20 PostLinks.xml
-rw-rw-r-- 1 user user  29G Apr 24 07:31 Post.xml
-rw-rw-r-- 1 user user 3.2M Apr 24 07:20 Tags.xml
-rw-rw-r-- 1 user user 895M Apr 24 06:00 Users.xml
-rw-rw-r-- 1 user user 6.1G Apr 24 05:59 Votes.xml
```

**Comment by stephanecollot** [comment]
Sorry my mistake, I think I renamed ````Posts.xml```` to ````Post.xml```` by mistake. I should work with ````Posts.xml```` I think. I will let you know.

**Comment by tessellator** [comment]
Thanks for opening this issue!  I look forward to hearing whether that fixes your problem.

**Comment by stephanecollot** [comment]
Ok, it works.
There is just Tags.xml that is not taken into account.
At the end, I also get errors on creation of keys, but I wasn't able to retrieve the errors, I lost my console history.

**Comment by tessellator** [comment]
Thanks for the heads up!  I will take a look into adding Tags and doing a better job of logging errors so we can get those smoked out.  Please let me know if you have any additional issues.
